name: Model Training

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run model training
        run: python src/train.py

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: data/models/
